main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Levi Muniz
description: Allow players to teleport between locations by interacting with mobs
softdepend:
  - Multiverse-Core

commands:
  mp:
    description: Base command for MobPortals
    usage: "For a list of commands, type /mp help"
    aliases: mobportals,mportals

permissions:
  mobportals.warp.*:
    description: Allows players to use all warps, or specify a warp name instead of *
    default: true
  mobportals.command.*:
    description: Allows players to use all command mobs, or specify a command mob name instead of *
    default: true
  mobportals.warp:
    description: Allows players to go to a warp using /mp warp
    default: op
  mobportals.listwarps:
    description: Allows players to list available warps
    default: op
  mobportals.admin.createcommand:
    description: Allows players to create command mobs with /mp create command
    default: false
  mobportals.admin.createportal:
    description: Allows players to create mob portals with /mp create portal
    default: false
  mobportals.admin.remove:
    description: Allows players to destroy mobs with /mp remove
    default: false
  mobportals.admin.setwarp:
    description: Allows players to create a warp using /mp setwarp
    default: false
  mobportals.admin.delwarp:
    description: Allows players to delete a warp using /mp delwarp
    default: false
  mobportals.admin.reload:
    description: Allows players to reload the plugin configuration
    default: false
  mobportals.*:
    description: Grants access to all portals and all other permissions
    default: false
    children:
      mobportals.warp: true
      mobportals.warp.*: true
      mobportals.command.*: true
      mobportals.listwarps: true
      mobportals.admin.createportal: true
      mobportals.admin.createcommand: true
      mobportals.admin.remove: true
      mobportals.admin.setwarp: true
      mobportals.admin.delwarp: true
      mobportals.admin.reload: true
  mobportals.admin.*:
    description: Grants access to all portals and other admin permissions
    default: op
    children:
      mobportals.warp.*: true
      mobportals.admin.createportal: true
      mobportals.admin.createcommand: true
      mobportals.admin.remove: true
      mobportals.admin.setwarp: true
      mobportals.admin.delwarp: true
      mobportals.admin.reload: true

