main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Levi Muniz
description: Interact with mobs like never before

commands:
  mact:
    description: Base command for MobActions
    usage: "For a list of commands, type /mact help"
    aliases: mobactions,mactions

permissions:
  mobactions.warp.*:
    description: Allows players to use all warps, or specify a warp name instead of *
    default: true
  mobactions.command.*:
    description: Allows players to use all commands, or specify a command alias instead of *
    default: true
  mobactions.warp:
    description: Allows players to go to a warp using /mp warp
    default: op
  mobactions.listwarps:
    description: Allows players to list available warps
    default: op
  mobactions.admin.createcommand:
    description: Allows players to create command mobs with /mp create command
    default: false
  mobactions.admin.createportal:
    description: Allows players to create portal mobs with /mp create portal
    default: false
  mobactions.admin.remove:
    description: Allows players to destroy mobs with /mp remove
    default: false
  mobactions.admin.setwarp:
    description: Allows players to create a warp using /mp setwarp
    default: false
  mobactions.admin.delwarp:
    description: Allows players to delete a warp using /mp delwarp
    default: false
  mobactions.admin.reload:
    description: Allows players to reload the plugin configuration
    default: false
  mobactions.*:
    description: Grants access to all mobs and all other permissions
    default: false
    children:
      mobactions.warp: true
      mobactions.warp.*: true
      mobactions.command.*: true
      mobactions.listwarps: true
      mobactions.admin.createportal: true
      mobactions.admin.createcommand: true
      mobactions.admin.remove: true
      mobactions.admin.setwarp: true
      mobactions.admin.delwarp: true
      mobactions.admin.reload: true
  mobactions.admin.*:
    description: Grants access to all mobs and other admin permissions
    default: op
    children:
      mobactions.warp.*: true
      mobactions.admin.createportal: true
      mobactions.admin.createcommand: true
      mobactions.admin.remove: true
      mobactions.admin.setwarp: true
      mobactions.admin.delwarp: true
      mobactions.admin.reload: true