main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Levi Muniz
description: Interact with mobs like never before

commands:
  mac:
    description: Base command for MobActions
    usage: "For a list of commands, type /mac help"
    aliases: mobactions,mactions

permissions:
  mobactions.warp.*:
    description: Allows players to use all warps, or specify a warp name instead of *
    default: true
  mobactions.command.*:
    description: Allows players to use all commands, or specify a command alias instead of *
    default: true
  mobactions.warp:
    description: Allows players to go to a warp using /mac warp
    default: op
  mobactions.admin.create:
    description: Allows players to create action mobs with /mac create
    default: false
  mobactions.admin.remove:
    description: Allows players to destroy mobs with /mac remove
    default: false
  mobactions.admin.warps.set:
    description: Allows players to create a warp using /mac warps set
    default: false
  mobactions.admin.warps.remove:
    description: Allows players to delete a warp using /mac warps remove
    default: false
  mobactions.admin.reload:
    description: Allows players to reload the plugin configuration
    default: false
  mobactions.admin.*:
    description: Grants access to all mobs and other admin permissions
    default: op
    children:
      mobactions.admin.create: true
      mobactions.admin.remove: true
      mobactions.admin.warps.set: true
      mobactions.admin.warps.remove: true
      mobactions.admin.reload: true
  mobactions.*:
    description: Grants access to all mobs and all other permissions
    default: false
    children:
      mobactions.warp: true
      mobactions.admin.*: true
      mobactions.command.*: true
      mobactions.warp.*: true