main: ${PACKAGE}.${NAME.toLowerCase()}.${NAME}
name: ${NAME}
version: ${VERSION}
api-version: "1.16"
author: Levi Muniz
description: Allow players to teleport between locations by interacting with mobs
commands:
  ex:
    description: Base command for EXAMPLE
    usage: "For a list of commands, type /ex help"
    aliases: example
permissions:
  example.test:
    description: DESCRIPTION
    default: true
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true