main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Levi Muniz
description: Interact with mobs like never before

commands:
  mac:
    description: Base command for MobActions
    usage: "For a list of commands, type /mac help"
    aliases: mobactions,mactions

permissions:
  mobactions.warp.*:
    description: Allows players to use all warps, or specify a warp name instead of *
    default: true
  mobactions.command:
    description: Allows players to use all command mobs
    default: true
  mobactions.consolecmd:
    description: Allows players to use all console command mobs
    default: true
  mobactions.event.*:
    description: Allows players to join all event, or specify an event name instead of *
    default: true
  mobactions.warp:
    description: Allows players to go to a warp using /mac warp
    default: op
  mobactions.admin.action.create:
    description: Allows players to create action mobs with /mac action create
    default: false
  mobactions.admin.action.remove:
    description: Allows players to destroy mobs with /mac action remove
    default: false
  mobactions.admin.warps.set:
    description: Allows players to create a warp using /mac warps set
    default: false
  mobactions.admin.warps.remove:
    description: Allows players to delete a warp using /mac warps remove
    default: false
  mobactions.admin.events.create:
    description: Allows players to create an event using /mac event create
    default: false
  mobactions.admin.events.remove:
    description: Allows players to remove an event using /mac event remove
    default: false
  mobactions.admin.events.start:
    description: Allows players to start an event using /mac events start
    default: false
  mobactions.admin.events.stop:
    description: Allows players to stop an event using /mac events stop
    default: false
  mobactions.admin.reload:
    description: Allows players to reload the plugin configuration
    default: false
  mobactions.admin.*:
    description: Grants access to all mobs and other admin permissions
    default: op
    children:
      mobactions.admin.reload: true
      mobactions.admin.action.create: true
      mobactions.admin.action.remove: true
      mobactions.admin.events.create: true
      mobactions.admin.events.remove: true
      mobactions.admin.events.start: true
      mobactions.admin.events.stop: true
      mobactions.admin.warps.set: true
      mobactions.admin.warps.remove: true

  mobactions.*:
    description: Grants access to all mobs and all other permissions
    default: false
    children:
      mobactions.warp: true
      mobactions.admin.*: true
      mobactions.command: true
      mobactions.consolecmd: true
      mobactions.warp.*: true
      mobactions.event.*: true